apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: webapp
              topologyKey: kubernetes.io/hostname
      containers:
        - name: webapp
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - containerPort: 3000
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secrets/key.json"
          volumeMounts:
            - mountPath: /secrets
              name: cloud-sql-proxy-sa-key
              readOnly: true
      volumes:
        - name: cloud-sql-proxy-sa-key
          secret:
            secretName: cloud-sql-proxy-sa-key  