apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PASSWORD
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/
          ports:
            - containerPort: 5432
      volumes:
        - name: init-sql
          configMap:
            name: init-sql