apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
          - "--private-ip"
          - "--auto-iam-authn"
          - "--structured-logs"
          - "--address=0.0.0.0"
          - "--credentials-file=/secrets/key.json"
        volumeMounts:
          - mountPath: /secrets
            name: cloud-sql-proxy-sa-key
            readOnly: true
      volumes:
        - name: cloud-sql-proxy-sa-key
          secret:
            secretName: cloud-sql-proxy-sa-key
